"""empty message

Revision ID: c48c7d1f56e8
Revises: 7ab6898a7c08
Create Date: 2023-06-04 09:40:10.710270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c48c7d1f56e8'
down_revision = '7ab6898a7c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
